// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/content_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5943226809940744062),
    name: 'ContentEntity',
    lastPropertyId: const obx_int.IdUid(8, 3798348028991207692),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4443996298609190745),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8868588840472862986),
        name: 'sourceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 918640951101263685),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4170606588270669003),
        name: 'author',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 544317078753679016),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5912226332218550649),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4776470097158223804),
        name: 'contentTypeIndex',
        type: 2,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3798348028991207692),
        name: 'embedding',
        type: 28,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5943226809940744062),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ContentEntity: obx_int.EntityDefinition<ContentEntity>(
      model: _entities[0],
      toOneRelations: (ContentEntity object) => [],
      toManyRelations: (ContentEntity object) => {},
      getId: (ContentEntity object) => object.id,
      setId: (ContentEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ContentEntity object, fb.Builder fbb) {
        final sourceIdOffset = fbb.writeString(object.sourceId);
        final titleOffset = fbb.writeString(object.title);
        final authorOffset = object.author == null
            ? null
            : fbb.writeString(object.author!);
        final contentOffset = fbb.writeString(object.content);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sourceIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, authorOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addInt64(5, object.createdDate.millisecondsSinceEpoch);
        fbb.addInt8(6, object.contentTypeIndex);
        fbb.addOffset(7, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final contentTypeIndexParam = const fb.Int8Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = ContentEntity(
          id: idParam,
          sourceId: sourceIdParam,
          title: titleParam,
          author: authorParam,
          content: contentParam,
          createdDate: createdDateParam,
          contentTypeIndex: contentTypeIndexParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ContentEntity] entity fields to define ObjectBox queries.
class ContentEntity_ {
  /// See [ContentEntity.id].
  static final id = obx.QueryIntegerProperty<ContentEntity>(
    _entities[0].properties[0],
  );

  /// See [ContentEntity.sourceId].
  static final sourceId = obx.QueryStringProperty<ContentEntity>(
    _entities[0].properties[1],
  );

  /// See [ContentEntity.title].
  static final title = obx.QueryStringProperty<ContentEntity>(
    _entities[0].properties[2],
  );

  /// See [ContentEntity.author].
  static final author = obx.QueryStringProperty<ContentEntity>(
    _entities[0].properties[3],
  );

  /// See [ContentEntity.content].
  static final content = obx.QueryStringProperty<ContentEntity>(
    _entities[0].properties[4],
  );

  /// See [ContentEntity.createdDate].
  static final createdDate = obx.QueryDateProperty<ContentEntity>(
    _entities[0].properties[5],
  );

  /// See [ContentEntity.contentTypeIndex].
  static final contentTypeIndex = obx.QueryIntegerProperty<ContentEntity>(
    _entities[0].properties[6],
  );

  /// See [ContentEntity.embedding].
  static final embedding = obx.QueryDoubleVectorProperty<ContentEntity>(
    _entities[0].properties[7],
  );
}
